In [2]:
import pandas as pd

# Especifique o caminho para o arquivo Excel
excel_file_path = r'E:\CentralDeAtendimento\Projetos\PainelCATPlus\arquivos_apoio\Distribuição de Demandas - Out2023.xlsx'

# Use a função read_excel para ler o arquivo Excel
xls = pd.ExcelFile(excel_file_path)

# Obtenha a lista de nomes de planilhas no arquivo
sheet_names = xls.sheet_names

# Itere pelas planilhas e carregue cada uma em um DataFrame do pandas
data = {}  # Dicionário para armazenar DataFrames de cada planilha

for sheet_name in sheet_names:
    data[sheet_name] = xls.parse(sheet_name)
    print(sheet_name)

# Agora você tem cada planilha em um DataFrame separado no dicionário 'data'
# Você pode acessar cada planilha pelo seu nome, por exemplo: data['NomeDaPlanilha']

PAINEL
Aprov. de estudos
Atestado, Declaração ou Certidã
Cancelamento de matrícula
Correção ou Alter. de Dados Cad
Data Especial de Col. de Grau
Ementas
Histórico Escolar
2ª Via Diploma de Grad.
2ª Via DiplomaCertif. de Pós-Gr
Trancamento
Reintegração
Nome Social
Restituição de taxa
Transferência(ex-officio)
Dilatação de curso
Disciplina Isolada
Outros
Nova Graduação na mesma ABI
Ingresso de Refugiados
Auxiliar
Urgência diploma digital

In [3]:
df_correcao_alteracao = data['Correção ou Alter. de Dados Cad']

# Transforma a primeira linha em cabeçalho
df_correcao_alteracao.columns = df_correcao_alteracao.iloc[0]

# Remove a primeira linha (opcional)
df_correcao_alteracao= df_correcao_alteracao[1:]

df_correcao_alteracao.columns

df_correcao_alteracao = df_correcao_alteracao[['ATRIBUÍDO PARA','STATUS','SETOR','DATA PROTOCOLO']]

df_correcao_alteracao.rename(columns={'ATRIBUÍDO PARA':'nome_operador','STATUS':'status','SETOR':'setor','DATA PROTOCOLO':'data_protocolo'},inplace=True)

In [4]:
df_correcao_alteracao.columns

Index(['nome_operador', 'status', 'setor', 'data_protocolo'], dtype='object', name=0)

In [5]:
df_correcao_alteracao['data_protocolo'] = df_correcao_alteracao['data_protocolo'].astype(str)

In [6]:
def separa_data(data_protocolo):
    return data_protocolo.split(' ')[0]


df_correcao_alteracao.data_protocolo = df_correcao_alteracao.data_protocolo.apply(separa_data)

df_correcao_alteracao

0    nome_operador       status                 setor data_protocolo
1             ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-03
2             ALAN  PROTOCOLADO                  SGLA     2023-10-02
3           RENATA  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-09
4             ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-03
5           RENATA    CANCELADO                  SGLA     2023-10-03
...            ...          ...                   ...            ...
1991           NaN          NaN                   NaN            nan
1992           NaN          NaN                   NaN            nan
1993           NaN          NaN                   NaN            nan
1994           NaN          NaN                   NaN            nan
1995           NaN          NaN                   NaN            nan

[1995 rows x 4 columns]

In [7]:
df_correcao_alteracao['data_protocolo'].unique()

array(['2023-10-03', '2023-10-02', '2023-10-09', '2023-10-04',
       '2023-10-05', '2023-10-11', '2023-10-17', '2023-10-19',
       '2023-10-24', 'nan', '2023-10-26', '2023-10-30', '2023-10-31',
       '2023-11-01', '2023-11-06', '2023-11-09', '2023-11-10',
       '2023-11-14'], dtype=object)

In [8]:
df_correcao_alteracao.dropna(inplace=True)

len(df_correcao_alteracao['nome_operador'])

26

In [10]:
df_correcao_alteracao

0  nome_operador       status                 setor data_protocolo
1           ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-03
2           ALAN  PROTOCOLADO                  SGLA     2023-10-02
3         RENATA  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-09
4           ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-03
5         RENATA    CANCELADO                  SGLA     2023-10-03
6           ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-04
7         RENATA  PROTOCOLADO                  SGLA     2023-10-04
8           ALAN  PROTOCOLADO                  SGLA     2023-10-04
9   ANA CRISTINA  PROTOCOLADO                  SGLA     2023-10-05
10  ANA CRISTINA  PROTOCOLADO                  SGLA     2023-10-11
11          ALAN  PROTOCOLADO                  SGLA     2023-10-11
12        RENATA  PROTOCOLADO                  SGLA     2023-10-17
13        RENATA  PROTOCOLADO                  SGLA     2023-10-19
14        RENATA  PROTOCOLADO                  SGLA     2023-10-24
16          ALAN  PROTOCOLADO  GMCA - Pós-Graduação     2023-10-26
17  ANA CRISTINA  PROTOCOLADO                  SGLA     2023-10-30
18          ALAN  PROTOCOLADO                  SGLA     2023-10-31
19  ANA CRISTINA  PROTOCOLADO                  SGLA     2023-11-01
20          ALAN  PROTOCOLADO                  SGLA     2023-11-06
21  ANA CRISTINA  PROTOCOLADO                  SGLA     2023-11-06
22        RENATA  PROTOCOLADO                  SGLA     2023-11-06
23        RENATA  PROTOCOLADO                  SGLA     2023-11-09
24        RENATA  PROTOCOLADO                  SGLA     2023-11-10
26  ANA CRISTINA  PROTOCOLADO                  SGLA     2023-11-09
29        RENATA  PROTOCOLADO  GMCA - Pós-Graduação     2023-11-14
30        RENATA  PROTOCOLADO  GMCA - Pós-Graduação     2023-11-14