In [1]:
import pandas as pd

# Especifique o caminho para o arquivo Excel
excel_file_path = r'E:\CentralDeAtendimento\Projetos\PainelCATPlus\arquivos_apoio\Distribuição de Demandas - Out2023.xlsx'

# Use a função read_excel para ler o arquivo Excel
xls = pd.ExcelFile(excel_file_path)

# Obtenha a lista de nomes de planilhas no arquivo
sheet_names = xls.sheet_names

# Itere pelas planilhas e carregue cada uma em um DataFrame do pandas
data = {}  # Dicionário para armazenar DataFrames de cada planilha

for sheet_name in sheet_names:
    data[sheet_name] = xls.parse(sheet_name)
    print(sheet_name)

# Agora você tem cada planilha em um DataFrame separado no dicionário 'data'
# Você pode acessar cada planilha pelo seu nome, por exemplo: data['NomeDaPlanilha']

PAINEL
Aprov. de estudos
Atestado, Declaração ou Certidã
Cancelamento de matrícula
Correção ou Alter. de Dados Cad
Data Especial de Col. de Grau
Ementas
Histórico Escolar
2ª Via Diploma de Grad.
2ª Via DiplomaCertif. de Pós-Gr
Trancamento
Reintegração
Nome Social
Restituição de taxa
Transferência(ex-officio)
Dilatação de curso
Disciplina Isolada
Outros
Nova Graduação na mesma ABI
Ingresso de Refugiados
Auxiliar
Urgência diploma digital

In [2]:
df_trancamento = data['Trancamento']

# Transforma a primeira linha em cabeçalho
df_trancamento.columns = df_trancamento.iloc[0]

# Remove a primeira linha (opcional)
df_trancamento= df_trancamento[1:]

df_trancamento.columns

df_trancamento = df_trancamento[['ATRIBUÍDO PARA','STATUS','SETOR','DATA PROTOCOLO']]

df_trancamento.rename(columns={'ATRIBUÍDO PARA':'nome_operador','STATUS':'status','SETOR':'setor','DATA PROTOCOLO':'data_protocolo'},inplace=True)

In [3]:
df_trancamento.columns

Index(['nome_operador', 'status', 'setor', 'data_protocolo'], dtype='object', name=0)

In [4]:
df_trancamento['data_protocolo'] = df_trancamento['data_protocolo'].astype(str)

In [5]:
def separa_data(data_protocolo):
    return data_protocolo.split(' ')[0]


df_trancamento.data_protocolo = df_trancamento.data_protocolo.apply(separa_data)

df_trancamento

0   nome_operador       status             setor data_protocolo
1            ALAN  PROTOCOLADO  GMCA - Graduação     2023-10-04
2          RENATA  PROTOCOLADO  GMCA - Graduação     2023-10-06
3          CARLOS  PROTOCOLADO  GMCA - Graduação     2023-10-04
4            ALAN  PROTOCOLADO  GMCA - Graduação     2023-10-06
5    ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-05
..            ...          ...               ...            ...
993           NaN          NaN               NaN            nan
994           NaN          NaN               NaN            nan
995           NaN          NaN               NaN            nan
996           NaN          NaN               NaN            nan
997           NaN          NaN               NaN            nan

[997 rows x 4 columns]

In [6]:
df_trancamento['data_protocolo'].unique()

array(['2023-10-04', '2023-10-06', '2023-10-05', '2023-10-16',
       '2023-10-18', '2023-10-19', '2023-10-24', '2023-10-25',
       '2023-11-14', '2023-10-31', '2023-11-01', 'nan', '2023-11-10',
       '2023-11-13'], dtype=object)

In [7]:
df_trancamento.dropna(inplace=True)

len(df_trancamento['nome_operador'])

21

In [8]:
df_trancamento

0  nome_operador       status             setor data_protocolo
1           ALAN  PROTOCOLADO  GMCA - Graduação     2023-10-04
2         RENATA  PROTOCOLADO  GMCA - Graduação     2023-10-06
3         CARLOS  PROTOCOLADO  GMCA - Graduação     2023-10-04
4           ALAN  PROTOCOLADO  GMCA - Graduação     2023-10-06
5   ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-05
6         RENATA  PROTOCOLADO  GMCA - Graduação     2023-10-16
7         CARLOS  PROTOCOLADO  GMCA - Graduação     2023-10-16
8         RENATA  PROTOCOLADO  GMCA - Graduação     2023-10-18
9   ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-18
10  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-19
11        RENATA  PROTOCOLADO  GMCA - Graduação     2023-10-24
12  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-24
13        CARLOS  PROTOCOLADO  GMCA - Graduação     2023-10-24
14  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-25
15        RENATA  PROTOCOLADO  GMCA - Graduação     2023-11-14
16  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-10-31
17  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-11-01
18        RENATA  PROTOCOLADO  GMCA - Graduação     2023-11-01
20        RENATA  PROTOCOLADO  GMCA - Graduação     2023-11-10
21  ANA CRISTINA  PROTOCOLADO  GMCA - Graduação     2023-11-13
22          ALAN  PROTOCOLADO  GMCA - Graduação     2023-11-14